# Generated by Django 2.2 on 2019-12-18 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mdrm', '0014_auto_20191217_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_link', models.CharField(max_length=256)),
                ('image', models.CharField(max_length=256)),
                ('meal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mdrm.Meal')),
            ],
        ),
    ]
