# Generated by Django 2.2 on 2019-12-16 00:09

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('mdrm', '0002_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Allergens',
            new_name='Allergen',
        ),
        migrations.RenameModel(
            old_name='DeliveryWindows',
            new_name='DeliveryWindow',
        ),
        migrations.RenameModel(
            old_name='Ingredients',
            new_name='Ingredient',
        ),
        migrations.RenameModel(
            old_name='Meals',
            new_name='Meal',
        ),
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='Recipes',
            new_name='Recipe',
        ),
        migrations.RenameModel(
            old_name='RecipeIngredients',
            new_name='RecipeIngredient',
        ),
        migrations.AlterModelManagers(
            name='profile',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
