# Generated by Django 2.2 on 2019-12-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdrm', '0005_meal_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverywindow',
            name='meals',
            field=models.ManyToManyField(related_name='delivery_windows', to='mdrm.Meal'),
        ),
    ]
