# Generated by Django 2.2 on 2019-12-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdrm', '0006_deliverywindow_meals'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverywindow',
            name='name',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
