# Generated by Django 2.2 on 2019-12-17 16:28

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('mdrm', '0007_deliverywindow_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='deliverywindow',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='meal',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
