# Generated by Django 2.2 on 2019-12-17 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdrm', '0010_auto_20191217_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='recipes',
            field=models.ManyToManyField(related_name='meals', to='mdrm.Recipe'),
        ),
    ]
