# Generated by Django 2.2 on 2019-12-17 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdrm', '0011_meal_recipes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.ManyToManyField(null=True, to='mdrm.Ingredient'),
        ),
    ]
