# Generated by Django 2.2 on 2019-12-18 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdrm', '0013_auto_20191217_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverywindow',
            name='meals',
        ),
        migrations.AddField(
            model_name='meal',
            name='serve_end',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meal',
            name='serve_start',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
