# Generated by Django 2.2 on 2019-12-18 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdrm', '0014_auto_20191217_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='recipes',
            field=models.ManyToManyField(blank=True, related_name='meals', to='mdrm.Recipe'),
        ),
    ]
