# Generated by Django 2.2 on 2019-12-14 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pearako', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='image_name',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
