# Generated by Django 2.2 on 2019-12-14 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pearako', '0002_projects_image_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='show_n_jewels',
            new_name='show_on_jewels',
        ),
    ]
