# Generated by Django 2.2 on 2019-12-14 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pearako', '0003_auto_20191214_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='show_on_bootcamp',
            field=models.BooleanField(default=False),
        ),
    ]
