# Generated by Django 2.2 on 2019-12-14 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pearako', '0004_projects_show_on_bootcamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='has_demo',
            field=models.BooleanField(default=False),
        ),
    ]
