# Generated by Django 2.2 on 2019-12-14 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pearako', '0005_projects_has_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='follow_up',
            field=models.TextField(blank=True),
        ),
    ]
