# Generated by Django 2.2 on 2019-12-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pearako', '0006_projects_follow_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='demo_link',
            field=models.TextField(blank=True),
        ),
    ]
