# Generated by Django 2.2 on 2019-12-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pearako', '0007_projects_demo_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='demo_link',
            field=models.CharField(blank=True, help_text='Leave blank for default demo path', max_length=256),
        ),
    ]
