# Generated by Django 2.2 on 2019-12-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pearako', '0008_auto_20191220_0707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='projects',
            name='technologies',
            field=models.ManyToManyField(related_name='project', to='pearako.Technologies'),
        ),
        migrations.AddField(
            model_name='projects',
            name='impages',
            field=models.ManyToManyField(related_name='project', to='pearako.Image'),
        ),
    ]
