# Generated by Django 2.2 on 2019-12-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pearako', '0010_auto_20191220_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_video',
            field=models.BooleanField(default=False),
        ),
    ]
