# Generated by Django 2.2 on 2019-12-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pearako', '0011_image_is_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='caption',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
