# Generated by Django 2.2 on 2019-12-25 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('is_video', models.BooleanField(default=False)),
                ('caption', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
                ('show_on_home', models.BooleanField(default=False)),
                ('show_on_jewels', models.BooleanField(default=False)),
                ('show_on_bootcamp', models.BooleanField(default=False)),
                ('has_demo', models.BooleanField(default=False)),
                ('demo_link', models.CharField(blank=True, help_text='Leave blank for default demo path', max_length=256)),
                ('github_link', models.CharField(blank=True, max_length=256)),
                ('external_link', models.CharField(blank=True, max_length=256)),
                ('image_name', models.CharField(blank=True, max_length=256)),
                ('description', models.TextField(blank=True)),
                ('the_ask', models.TextField(blank=True)),
                ('challenges', models.TextField(blank=True)),
                ('solution', models.TextField(blank=True)),
                ('follow_up', models.TextField(blank=True)),
                ('images', models.ManyToManyField(blank=True, related_name='project', to='portfolio.Image')),
                ('technologies', models.ManyToManyField(related_name='project', to='portfolio.Technology')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('projects', models.ManyToManyField(related_name='page', to='portfolio.Project')),
            ],
        ),
    ]
