# Generated by Django 2.2 on 2020-01-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_page_is_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, help_text='This text will appear in project listings as well as the page for this project'),
        ),
    ]
